### ISSUE TITLE
RFC: v4

### ISSUE THREAD

**Issue by MatthewHerbst** [brigade/eslint-config-brigade#13]
Internally at Brigade we are working on some big new projects. This is a chance for us to make major linting decisions that we may have deferred - or simply not considered, in the past.

I'd like to take recommended settings from ESLint, eslint-plugin-react, and Airbnb, and add/override where needed rather than try to specify everything ourselves. This should make the config a little easier to read (since I would argue most people are familiar with the defaults). It will also make staying up-to-date with the latest and greatest simpler.

**Proposed changes:**

- [x] In the base config, extend `"eslint:recommended"`
- [x] In the react config, extend `"plugin:react/recommended"`
- [x] ~~Since we follow the [Airbnb style-guide](https://github.com/airbnb/javascript), add `eslint-config-airbnb` as a dependency. We then have two options:~~
    - [x] ~~Extend `"airbnb"` in the base config. This seems fine to me, but will mean that non-base Airbnb rules such as Airbnb's React rules will be included in the config. I don't think there is any harm to this, though I understand why it might not be desired.~~
    - [x] ~~Extend `"airbnb/eslint-config-airbnb-base"` in the base config, and extend `"airbnb"` in the react config. This will ensure we have no "extra" rules in the base config.~~
- [x] Remove all existing rules that are the same as that rule in one of the extended configs (if it exists there)
- [x] Investigate [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) rules and implement accordingly
- [x] Investigate [`eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y) plugin rules and implement accordingly
- [x] Add a `yarn.lock` file to support [`yarn`](https://yarnpkg.com/en/).
- [X] Implement peer dependencies (@steverice) (**[Done](https://github.com/brigade/eslint-config-brigade/pull/16)**)
- [x] Remove all but `eslint` from `peerDependencies` 
- [x] Implement multiple entry points. Ex: `import eslintConfigBrigadeReact from 'eslint-config-brigade/react'`. This would imply merging [`eslint-config-brigade-node`] (**MOVED** to #18)(https://github.com/brigade/node-style/tree/master/packages/eslint-config-brigade-node) into this repo for access via `import eslintConfigBrigadeNode from eslint-config-brigade/node`
- [x] Officially support npm3+  = add [`engines`](https://docs.npmjs.com/files/package.json#engines) entry to `package.json`.

**Comment by steverice** [comment]
We should also make `eslint` [a peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/#the-problem-plugins), as this preset does not directly depend on it.

**Comment by MatthewHerbst** [comment]
@lencioni ^ should resolve the dev/not dependency issue from https://github.com/brigade/eslint-config-brigade/pull/15

**Comment by MatthewHerbst** [comment]
Add an [`engines`](https://docs.npmjs.com/files/package.json#engines) entry. We will officially be supporting only npm >= 3 with v4 of this repo.

**Comment by MatthewHerbst** [comment]
After some discussion, we will **NOT** be extending the Airbnb configs. We will be using them as references for decision making, but the existing rule review plus our own style changes means it doesn't make much sense for us to extend Airbnb.

**Comment by MatthewHerbst** [comment]
We already have multiple entry points for the base and React configs. Implementing the node entry point will be a larger body of work, and will be completed in v4.X
